name: 'GitHub Action for creating a GitHub Repository'
description: 'This is a GitHub Action for creating a GitHub Repository.'

branding:
  icon: plus-square
  color: 'blue'

inputs:
  repo-name:
    description: 'The name of the repository'
    required: true
  repo-private:
    description: 'The private of the repository'
    required: true
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
